var resultText = Text ? "Aの処理" : "Bの処理";
console.log(resultText);
console.log("trueはAの処理です。");
var resultNum = 5 > 4 ? true : false;
console.log(resultNum);
console.log("5は4よりも大きい");
var resultNum = 4 > 5 ? true : false;
console.log(resultNum);
console.log("4は5よりも小さい");
var resultNum = 5 > 3 ? true : false;
console.log(resultNum);
console.log("3は5よりも小さい");
var resultNum = 3 > 5 ? true : false;
console.log(resultNum);
console.log("3は5よりも小さい");
var resultNum = 15 > 10 ? true : false;
console.log(resultNum);
console.log("15は10以上");
var resultNum = 5 > 10 ? true : false;
console.log(resultNum);
console.log("5は10以下");
var resultText = "boolean" ? true : false;
console.log(resultText);
console.log("値が存在する");
var resultText = "" ? true : false;
console.log(resultText);
console.log("値が存在しない");